server:
  port: 8080
#  port: 8443
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-type: PKCS12
#    key-store-password: 1234
#    key-alias: tomcat

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.2:33066/example
    username: root
    password: root

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

